export const authConstants = {
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
}

export const registerConstants = {
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE'
}

export const categoryConstants = {
    GET_ALL_CATEGORY_REQUEST : "GET_ALL_CATEGORY_REQUEST",
    GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
    GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",
    ADD_CATEGORTY_REQUEST: 'ADD_CATEGORTY_REQUEST',
    ADD_CATEGORTY_SUCCESS: 'ADD_CATEGORTY_SUCCESS',
    ADD_CATEGORTY_FAILURE: 'ADD_CATEGORTY_FAILURE',
    UPDATE_CATEGORIES_REQUEST:'UPDATE_CATEGORIES_REQUEST',
    UPDATE_CATEGORIES_SUCCESS: 'UPDATE_CATEGORIES_SUCCESS',
    UPDATE_CATEGORIES_FAILURE: 'UPDATE_CATEGORIES_FAILURE',
    DELETE_CATEGORIES_REQUEST: 'DELETE_CATEGORIES_REQUEST',
    DELETE_CATEGORIES_SUCCESS:'DELETE_CATEGORIES_REQUEST',
    DELETE_CATEGORIES_FAILURE:'DELETE_CATEGORIES_FAILURE'
}

export const productConstants = {
    GET_ALL_PRODUCT_REQUEST : "GET_ALL_PRODUCT_REQUEST",
    GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
    GET_ALL_PRODUCT_FAILURE: "GET_ALL_PRODUCT_FAILURE", 
    ADD_PRODUCT_REQUEST:'ADD_PRODUCT_REQUEST',
    ADD_PRODUCT_SUCCESS:'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAILURE:'ADD_PRODUCT_FAILURE'
   
}
export const pageConstant = {
    CREATE_PAGE_REQUEST : 'CREATE_PAGE_REQUEST',
    CREATE_PAGE_SUCCESS:'CREATE_PAGE_SUCCESS',
    CREATE_PAGE_FAILURE:'CREATE_PAGE_FAILURE'
}