

export const categoryConstants = {
    GET_ALL_CATEGORY_REQUEST : "GET_ALL_CATEGORY_REQUEST",
    GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
    GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",
    ADD_CATEGORTY_REQUEST: 'ADD_CATEGORTY_REQUEST',
    ADD_CATEGORTY_SUCCESS: 'ADD_CATEGORTY_SUCCESS',
    ADD_CATEGORTY_FAILURE: 'ADD_CATEGORTY_FAILURE'
}
export const productConstant = {
    GET_PRODUCT_BY_SLUG_REQUEST:'GET_PRODUCT_BY_SLUG_REQUEST',
    GET_PRODUCT_BY_SLUG_SUCCESS: 'GET_PRODUCT_BY_SLUG_SUCCESS',
    GET_PRODUCT_BY_SLUG_FAILURE: 'GET_PRODUCT_BY_SLUG_FAILURE',
    
    GET_PRODUCT_BY_PAGE_REQUEST:'GET_PRODUCT_BY_PAGE_REQUEST',
    GET_PRODUCT_BY_PAGE_SUCCESS:'GET_PRODUCT_BY_PAGE_SUCCESS',
    GET_PRODUCT_BY_PAGE_FAILURE: 'GET_PRODUCT_BY_PAGE_FAILURE',
    

    GET_PRODUCT_DETAILS_BY_ID_REQUEST:'GET_PRODUCT_DETAILS_BY_ID_REQUEST',
    GET_PRODUCT_DETAILS_BY_ID_SUCCESS:'GET_PRODUCT_DETAILS_BY_ID_SUCCESS',
    GET_PRODUCT_DETAILS_BY_ID_FAILURE:'GET_PRODUCT_DETAILS_BY_ID_FAILURE'
}
export const authConstants = {
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
}

export const cartConstants = {
    ADD_TO_CART_REQUEST:'ADD_TO_CART_REQUEST',
    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAILURE:'ADD_TO_CART_FAILURE',
    RESET_CART:'RESET_CART'
}

export const userConstansts = {
    GET_USER_ADDRESS_REQUEST:'GET_USER_ADDRESS_REQUEST',
    GET_USER_ADDRESS_SUCEESS:'GET_USER_ADDRESS_SUCEESS',
    GET_USER_ADDRESS_FAILURE:'GET_USER_ADDRESS_FAILURE',
    ADD_USER_ADDRESS_REQUEST:'ADD_USER_ADDRESS_REQUEST',
    ADD_USER_ADDRESS_SUCEESS:'ADD_USER_ADDRESS_SUCEESS',
    ADD_USER_ADDRESS_FAILURE:'ADD_USER_ADDRESS_FAILURE',
    ADD_USER_ORDER_ADDRESS_REQUEST: 'ADD_USER_ORDER_ADDRESS_REQUEST',
    ADD_USER_ORDER_ADDRESS_SUCEESS:'ADD_USER_ORDER_ADDRESS_SUCEESS',
    ADD_USER_ORDER_ADDRESS_FAILURE:'ADD_USER_ORDER_ADDRESS_FAILURE',
    GET_USER_ORDER_ADDRESS_REQUEST: 'GET_USER_ORDER_ADDRESS_REQUEST',
    GET_USER_ORDER_ADDRESS_SUCEESS:'GET_USER_ORDER_ADDRESS_SUCEESS',
    GET_USER_ORDER_ADDRESS_FAILURE:'GET_USER_ORDER_ADDRESS_FAILURE'


}